### PR TITLE
Add Timing Channels to report execution unit duration

### PR DESCRIPTION
**Pull request by Karl-G1**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-aim-arinc429-custom-device/blob/main/CONTRIBUTING.md).

### What does this Pull Request accomplish?

- Add "Timing Channels" to the custom device
  - Four timing channels are created (one per execution unit that takes lots of processing time)
  - These are currently created by default when the CD is initialized, but later we will make it optional via RTM
- Create mechanism for storing the Incoming Channel index offset and current execution time per execution unit to report execution duration to the appropriate timing channel
  - Add accessors to the Execution Unit implementation for `Timing Offset` and `Current Execution Time`
  - Add methods and overrides to the Execution Unit interface and implementation for `Update Current Execution Time` and `Write Execution Time`
  - Set the offset to a non-negative (valid) value when creating each execution unit
  - Use the offset to replace the array element of the incoming channel data array per execution unit
- Create two new sub VIs for use in the engine (`Timed Read from Hardware` and `Timed Write to Hardware`)
  - These call into the respective existing VIs and use the microsecond tick count VI to calculate execution time
  - Because the Write VI does not modify the incoming data, store the Current Execution Time
  - In the Read VI, add its duration and the current execution time, then update the value in the data array
- Add system explorer page, help, GUID, properties, etc. for the additional channels
- Add a unit test for scripting in Timing Channels

### Why should this Pull Request be merged?

This custom device spends a lot of CPU time making driver calls. We have added the ability to run the Rx execution unit asynchronously from the PCL (and therefore not blocking the max loop rate of the rest of the system). However, users will not know what rate they _can_ run the system without a way of determining the async execution unit duration. 

### What testing has been done?

- Deployed with various system configurations (scaling from 2x channels to 8x channels) to see execution time increase as expected
- Deployed with acyclic Tx channels and logging enabled
- Ran test suite (except the failing test addressed in #96)
image
image

### CODE REVIEW

**Review by buckd — COMMENTED** [review]
There doesn't need to be a new method on the `Execution Unit` interface to get the timing channel offset. It makes more sense to create a method that writes the execution time to the values array (and maybe one that stores an intermediate, current execution time, if it needs to be split across the `Read` and `Write` calls.

`Read from Hardware` and `Write to Hardware` already take in the full array of values and do all the updates within those calls. It would be nice to do a similar thing for timing channels instead of having raw updates on calling diagrams, which make it trickier to read the overall code, even though it might be useful for probing.

The `Execution Unit` class can still keep the timing offset in its class data, but `Timed Read from Hardware` and `Timed Write to Hardware` can call interface VIs that update the current time and then write that time to the values array when required.

Something like below would probably work if you also had accessors for get/set the execution time. Then, `Timed Read` and `Timed Write` could have an input to determine when the value update is actually called. This solves the current problem of tracking both write and read times in an inline execution unit (although it's not really relevant for this custom device).

image
image


- [x] It's weird that get a timing ref in the scripting API returns an array since there is only one timing channel ref. The API should return a scalar and when it's placed into the **Incoming Channels** array, make it an array there, if necessary.
- [x] `Execution Unit.Async.vi` - The iteration terminal that is indexing the array can't be seen. I guess it's hiding under the structure?
image

**Comment by Karl-G1** [comment]
@buckd I made a lot of changes based on the approach you suggested. I'll update the PR notes accordingly, but the biggest changes are:
- Scripting API implementation (return refs instead of arrays)
- Write timing values from inside Timed Read from Hardware
- Store timing value inside Timed Write to Hardware
- Add a helper VI to use in the Create Execution Units.vi for conditionally building an array

**Review by buckd — COMMENTED** [review]
- [ ] `Timed Write to Hardware.vi` should change the **Valid** terminal name to be **Triggers Valid** so I actually know what is valid.
- [ ] `Tx Scheduled Labels Execution Unit:Write to Hardware.vi` has no changes.
- [ ] `Execution Unit` interface `Update Current Execution Time.vi` should have **Current Execution Time (us)** required.
- [ ] `Execution Unit` interface `Write Execution Time.vi` should have **Values in** required.

**Comment by Karl-G1** [comment]
I rebuilt fixed the Execution Unit implementation, rebuilt the PPLs (which would have caught that issue... oops), and re-ran the test suite. Everything looks good to go now.
image

**Pull request merged**
